# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    inputs:
      targetType: 'filePath'
      filePath: 'ci/run_unit_tests.sh'
      workingDirectory: 'app/'

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
      scanReportTimeout: '1'
